//! PROYECTOS
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const SELECCIONAR_PROYECTO = 'SELECCIONAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

//!TAREAS
export const OBTENER_TAREAS = "OBTENER_TAREAS";
export const AGREGAR_TAREA = "AGREGAR_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const CAMBIAR_ESTADO = "CAMBIAR_ESTADO";
export const OBTENER_TAREA_EDITAR = "OBTENER_TAREA_EDITAR";
export const EDITAR_TAREA = "EDITAR_TAREA";

